### ISSUE TITLE
MathJax rendered as lines

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/quiz-renderer#10]
![screenshot from 2016-01-04 21-42-43](https://cloud.githubusercontent.com/assets/13518486/12099958/23ad93d4-b32c-11e5-905c-3ebc30c7c1c5.png)

On attached screenshot are Latex rendered as lines instead of the equations.

I can reproduce this by:

* start new quiz
* press Page Down till you see a MathJax equation
* click back in the quiz bar
* return to quiz
* press Page Down till you see a MathJax equation

Using Firefox 43.0

**Comment by iainbryson** [comment]
Interesting.  It looks like this is a result of moving to SVG MathJax to resolve the aliasing bug noted previously.

What seems to be happening is that the SVG MathJax renderer stashes a bunch of re-used components in a DIV in the document.  For some reason, on nav (but not on reload) it isn't doing this, resulting in the weird lines.  

I can work around this by turning off the global cache (as these re-used components are called, at the cost of increasing the page side for the renderer.

useGlobalCache: false;

https://mathjax.readthedocs.org/en/latest/options/SVG.html

I'll see if there are any other (inexpensive) options.  Otherwise I'll remove the global cache.

**Comment by iainbryson** [comment]
Fixed
